version: "3.7"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gorm

  # Production container. Builds in release mode and run. Project will be restarted on every abort.
  api:
    hostname: app-production
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      PORT: "3000"
    volumes:
      - type: bind
        source: .
        target: /home/app
    working_dir: /home/app
    ports:
      - "3000:3000"
    command: bash -c "go mod download && go build -o /bin/app main.go && /bin/app"
    depends_on:
      - db
