# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: "3.7"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  api:
    # refer to -> https://github.com/cosmtrek/air#docker-compose
    image: cosmtrek/air
    working_dir: /app
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
